version: '1'

services:

  master_postgres:
    image: postgres:13.3
    container_name: clean_codeDB
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
  master_redis:
    image: redis/redis-stack:latest
    container_name: clean_codeRedis
    ports:
      - "6379:6379"

