spring:
  application:
    name: clean_code

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      port: 6379
      host: localhost

  liquibase:
    change-log: classpath:db.changelog/db-changelog.master.yaml
    enabled: true

  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        keep-alive: 60
        queue-capacity: 10000

logging:
  level:
    liquibase: debug

clean_code:
  transaction:
    batch: 100

server:
  port: 8185
